### ISSUE TITLE
SSL certificate unsave NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by thorbenegberts** [Hammertime-Kassel/htks#24]
https://hammertimekassel.de/

Error: NET::ERR_CERT_COMMON_NAME_INVALID

<img width="701" alt="bildschirmfoto 2017-08-18 um 14 00 59" src="https://user-images.githubusercontent.com/3115618/29458091-b5318a18-841d-11e7-81a3-c85f59a347d0.png">

**Comment by thorbenegberts** [comment]
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

**Comment by alinmigea** [comment]
from what I could see in the blog, that's not a fully secure setup, but I think that we should consider it. Maybe we could speak tomorrow.

**Comment by thorbenegberts** [comment]
I'm not there tomorrow…

It seems that we don't have any forms on our website that doesn't already send data to a secure location (e.g. our contact form). But we have to check it.

**Comment by thorbenegberts** [comment]
We now have a valid SSL certificate. Closed.
